### ISSUE TITLE
The form is not save when the create form is error

### ISSUE THREAD

**Issue by HelloYeew** [beattosetto/beattosetto#197]
When the form is error, the form will all disappear and just show the error.

**Comment by pontakornth** [comment]
Can you provide detail which forms display such errors?

**Comment by HelloYeew** [comment]
https://user-images.githubusercontent.com/68165621/142430485-2b3a4ee0-0c94-431b-aad7-0f60faea37d5.MOV

From this, it must contain all of the old form and you can edit and fix the error then submit. But it's all disappear instead.

**Comment by pontakornth** [comment]
This is a natural behavior of Django.
