### ISSUE TITLE
The system login for users automatically after create new accounts.

### ISSUE THREAD

**Issue by NamoSmith** [beattosetto/beattosetto#220]
- Test create new account.  
![image](https://user-images.githubusercontent.com/74136783/142965614-5a3c4faf-444b-4d23-b1e5-bfbfad554362.png)
- After I clicked the submit button for creating new account, then I was logged in automatically.  
![image](https://user-images.githubusercontent.com/74136783/142965683-b95f60f8-d4df-48ca-8e4b-3f043a30484e.png)

## How to reproduce
I think the system should just create new accounts for users, and then maybe navigate them to login page for convenience .

**Comment by HelloYeew** [comment]
I think that the usage is already alright now.  I think that few people is register without logging in to the website.

**Comment by pontakornth** [comment]
It's actually a feature. It's intended to work this way.
